jobs:
  include:
     - stage: preflight
       env: TASK=travis-format

    - stage: libraries
      env: SBT_PROJECT=common

    - stage: services
      env: SBT_PROJECT=items_api
    - env: SBT_PROJECT=requests_api

script:
  - ./run_travis.py

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - project/target
    - target

    - common/target

    - items_api/target
    - requests_api/target

stages:
  - preflight
  - libraries
  - services

before_install:
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in secrets.zip.enc -out secrets.zip -d
  - unzip secrets.zip
  - chmod 600 id_rsa
  - mkdir -p ~/.aws
  - cp config ~/.aws/config
  - cp credentials ~/.aws/credentials

language: sh

services:
  - docker

dist: trusty

branches:
  only:
    - master

before_cache:
  # Based on instructions from
  # https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html#Caching
  - sudo find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - sudo find $HOME/.sbt        -name "*.lock"               -print -delete

env:
  global:
    # This forces Python to print everything to stdout/stderr immediately.
    # Otherwise, we've seen issues where all the output from our Travis scripts
    # gets buffered, and only gets printed at the end of the test...
    #
    # ... out of order from the rest of the rest of the output!
    #
    # See also: https://docs.python.org/3/using/cmdline.html#cmdoption-u
    #
    - PYTHONUNBUFFERED=x
